name: Run CI checks

on: [pull_request]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
             - uses: actions/checkout@v1
             - uses: bahmutov/npm-install@v1.4.5
             - run: npm run nx affected -- --target=lint --parallel --base=origin/master --head=HEAD
             - run: npm run nx affected -- --target=build --parallel --base=origin/master --head=HEAD --prod
             - run: npm run nx affected -- --target=test --parallel --base=origin/master --head=HEAD
