name: Run CI checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
             - uses: actions/checkout@v1
             - uses: bahmutov/npm-install@v1.4.5
             - run: npm run nx affected:lint --parallel --base=origin/master --head=HEAD
             - run: npm run nx affected:build --parallel --base=origin/master --head=HEAD
             - run: npm run nx affected:test --parallel --base=origin/master --head=HEAD
